language: node_js
node_js:
  # Node 8 is the earliest supported version for eslint
  # See https://github.com/eslint/eslint/issues/11944
  - "8"
before_script:
  - npm run build
script:
  - npm run lint
  - npm run test
after_success: npm run coverage
